server:
  port: 10011
spring:
  application:
    name: server-consumer-houtai1
  redis:
    host: localhost
    database: 0
    password:
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka