server:
  port: 9090
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 60
    lease-expiration-duration-in-seconds: 90

  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    healthcheck:
        enabled: true

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

