server:
  port: 10012
spring:
  application:
    name: server-consumer-houtai2
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
