server:
  port: 10030
spring:
  application:
    name: server-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
zuul:
  routes:
    houtai:
      path: /houtai/**
      serviceId: server-consumer-houtai1